class Config {
  static String user_name = '';
  static List<String> gammeNameList = [
    'Doom/Hexen/Heretic triple pack',
    'The Space game',
    'Magic Pen',
    'N Game',
    'Desktop Tower Defence',
    'Tetris',
    'Stick Cricket',
    'Puzzle Bobble',
    'Mansion Impossible',
    'Super Mario World',
    'Gravity Pods',
    'Kill the Popups',
    'Boomshine',
    'Penjuin jumping',
    'Tennis',
    'The Killer Flu Game',
    'Free Rice',
    'Sock and Awe',
    'The Helicopter Game',
    'The Game of Disorientation',
  ];
  static List<String> gammeContentList = [
    'Doom, the best game of all time, is now available in Flash. We dont have to sell it to you, its Doom. Warning: This game has bloody and brutal graphics and is not suitable for children.',
    'Mining asteroids in space while defending against space pirates -- its that simple. But you need the balance between power, defense, exploitation, and stratagem that makes the game fun and addictive. Dont do it at work',
    'This is a lovely, innovative puzzle game that requires you to push a clumsy drawing ball to reach some flags. To do that, you can draw something yourself that moves under gravity and pushes the drawing ball around. It sounds really strange, but the game is very intuitive.',
    'A maniacal ninja keeps jumping around, the little man sketched out in a few simple strokes rapidly jumping from one platform to another, until he quickly falls from the top and -- according to common sense -- inevitably dies. Its fun, but its tricky -- very, very tricky.',
    'There are hundreds of "tower defense" strategy games on the Internet, but this one is one of the most popular. The rules were common: build turrets to defend the base against hordes of intruders.',
    'Tetris. Do we need to give you a screenshot of the game? The bricks fall, you rotate them into place, and if they form a horizontal line, the line disappears. Russian music plays in the background. This is Tetris, you know.',
    'If Football Manager is the game most mentioned in divorce cases, Cricket is probably on a P45 (or pink slip, if youre American). Is there a baseball game? The most photographed game ever. (Pink slips are P45 in the UK, pink slips in the US)',
    'Players of a certain age will remember the arched machine in the playful Bubble Bubble game. The flash-inspired nostalgia is like watching a clip from Round The Twist or hearing Wham Bar again',
    'Buying a house and selling it for a profit doesnt sound like a game -- if anything, it sounds like the lifestyle of the kind of money-soaked guys who laugh and talk and you avoid at parties. But this game is fun, and I cant help but be impressed.',
    'This is another game that goes without saying. Navigating a chubby Italian plumber through a bizarre cartoon world, eating gold coins, eating mushrooms and rescuing princesses. Thats obviously the case',
    'A simple rule - shoot with a gun and let a ball hit the target. But the ball will be deflected by small gravity pods, which will be used to steer the ball around obstacles and hit its target.',
    'Its also called Reality Web Simulator, and its brought by a bunch of nice guys from B3TA (you might struggle to call them nice guys).',
    'A slightly strange puzzle (if its described correctly) in which you have to trigger a series of explosions at dots that float around the screen.',
    'Can make people temporarily happy, but extraordinarily surreal. Put a penguin on a diving board, do a triple somerset and dive, or whatever, and a seal pup, a walrus and (presumably) a polar bear score it on take-off height, spin and entry Angle.',
    'Owners of NES, the ancient gaming platform, will love this tennis game. It was essentially a direct copy of Nintendos old tennis game. Oh, and all you have to do is hit the ball with the racket and get it over the net. Youll get the hang of it in no time',
    'Produced by the UK-based Clinical Virology Network to educate us about the spread of pandemic influenza, both pandemic influenza and everyday seasonal flu. Normally we dont care about that, we just want to spread something like the plague of modern times, but when we do that, we might learn a thing or two.',
    '"This is Balderdash or Call My Bluff -- it asks you what the word means and you have to choose from four options, three of which are wrong. The words get harder and harder until you try to guess what ""erose"" means (apparently ""irregular"").But every time you answer a question correctly, the site donates 10 grains of rice to the United Nations World Food Program. So while youre learning, youre tackling world hunger. Thats it."',
    'Have you ever wanted to throw a leather shoe at former US President George W. Bush but wished you could not make it to a press conference in Baghdad? Now you have one. Nearly 100 million shoes have hit poor Bush since the start of this little game, and his face is a look of disbelief.',
    'Its as simple as this -- hold down the left button to make the helicopter go up; Release the left button and the plane will descend. The plane will automatically move forward, you have to dodge obstacles to see how far you can go. The answer is probably "not very far," if youre anything like us',
    'All you have to do is walk towards the target, but the rotating camera and weird zooming effects make it harder. If you are prone to seasickness, it is recommended not to play.',
  ];
}
